### ISSUE TITLE
clientconfig.NewServiceClient : OS_CLOUD overrides clientOpts.Cloud

### ISSUE THREAD

**Issue by az-blip** [gophercloud/utils#164]
Hi,

I found out that in the `clientconfig.GetCloudFromYAML` method, the environment value of OS_CLOUD always overrides the specified value in `clientOpts.Cloud`.
https://github.com/gophercloud/utils/blob/d7085207ff6d2f5145138a813cc37e45c74e2000/openstack/clientconfig/requests.go#L197-L213

It seems the wrong priority to me, as the value defined in my program is more precise and could even be changed by the user (command line arg for example), while the environnement variable is more like a default value.
Could it be possible to modify this behavior ?

Alain Z.

**Comment by mdbooth** [comment]
Yes, I also wasted half a day and half a head of hair before working this one out.

**Comment by pierreprinetti** [comment]
Here's a way to make Gophercloud ignore environment variables when parsing `clouds.yaml`:

```Go
cloud, err := clientconfig.GetCloudFromYAML(&clientconfig.ClientOpts{
	Cloud:     cloudName,
	EnvPrefix: "NO_OPENSTACK_ENV_VARIABLES_",
})
```
Not what we want, but what we need.

In the meantime, shall we create a similar function that does NOT take into account env vars, and deprecate this one (without removing it)?

**Comment by mdbooth** [comment]
Just realising that my problem was related, but different. Specifically in my case I was passing a populated ClientOpts (containing AuthInfo) to clientconfig.AuthOptions(). In this case AuthOptions tries to fetch a cloud from the environment, and only uses the explicitly passed AuthInfo if it doesn't find one:

https://github.com/gophercloud/utils/blob/d7085207ff6d2f5145138a813cc37e45c74e2000/openstack/clientconfig/requests.go#L366-L388

The behaviour I expect is the opposite of this. i.e. If AuthInfo was explicitly passed to the function we use it directly, and if it wasn't we look for a cloud from the environment. So don't remove the (very useful) ability to fetch a cloud from the environment, it just shouldn't override explicitly passed AuthInfo.

**Comment by jtopjian** [comment]
Some background on this file: The bulk of the work was done in April/May 2018. Unfortunately my code comments link to the "master" branch, which wasn't good for posterity, but this would have been the approximate commit that I based `clientconfig/requests.go` off of:

https://github.com/openstack/os-client-config/blob/64b28d42eda595a6fb4ee8b46d93cd61e612aae1/os_client_config/config.py

It looks like I either missed or disagreed with the way `OS_CLOUD` is handled: if the environment variable is set and if there's a matching entry in `clouds.yaml`, then an error is returned. So technically this file _should_ do the same, though I'm surprised at not being able to use `OS_CLOUD` to choose the entry from `clouds.yaml`.

To confirm though: all other `OS_*` variables should have priority over any other value passed in. Unless I'm mistaken, this is how the Python library works.

It looks like `OS_CLOUD` should be handled as a special case, though.

**Comment by mdbooth** [comment]
> Some background on this file: The bulk of the work was done in April/May 2018. Unfortunately my code comments link to the "master" branch, which wasn't good for posterity, but this would have been the approximate commit that I based `clientconfig/requests.go` off of:
> 
> https://github.com/openstack/os-client-config/blob/64b28d42eda595a6fb4ee8b46d93cd61e612aae1/os_client_config/config.py
> 
> It looks like I either missed or disagreed with the way `OS_CLOUD` is handled: if the environment variable is set and if there's a matching entry in `clouds.yaml`, then an error is returned. So technically this file _should_ do the same, though I'm surprised at not being able to use `OS_CLOUD` to choose the entry from `clouds.yaml`.
> 
> To confirm though: all other `OS_*` variables should have priority over any other value passed in. Unless I'm mistaken, this is how the Python library works.
> 
> It looks like `OS_CLOUD` should be handled as a special case, though.

I wonder if @stephenfin could comment on the behaviour of the python library. Is there an analogous case?

**Comment by stephenfin** [comment]
Unfortunately the answer is "it's complicated". `openstackclient` is a consumer of `openstack` so it's a good case study. Consider the following `clouds.yaml`:

```yaml
clouds:                                                                                                                                                                                                            
    devstack:                                                                                                                                                                                                      
        auth:                                                                                                                                                                                                      
            auth_url: http://10.0.108.84/identity                                                                                                                                                                  
            password: password                                                                                                                                                                                     
            project_domain_id: default                                                                                                                                                                             
            project_name: demo                                                                                                                                                                                     
            user_domain_id: default                                                                                                                                                                                
            username: demo                                                                                                                                                                                         
        identity_api_version: '3'                                                                                                                                                                                  
        region_name: RegionOne                                                                                                                                                                                     
        volume_api_version: '3'                                                                                                                                                                                    
    devstack-admin:                                                                                                                                                                                                
        auth:                                                                                                                                                                                                      
            auth_url: http://10.0.108.84/identity                                                                                                                                                                  
            password: password                                                                                                                                                                                     
            project_domain_id: default                                                                                                                                                                             
            project_name: admin                                                                                                                                                                                    
            user_domain_id: default                                                                                                                                                                                
            username: admin                                                                                                                                                                                        
        identity_api_version: '3'                                                                                                                                                                                  
        region_name: RegionOne
        volume_api_version: '3'
```

Firstly, if you have an environment variable and an explicit option (e.g. `OS_CLOUD` and `--os-cloud`) then the latter takes priority:

```
# using environment variable for admin cloud credentials
$ OS_CLOUD=devstack-admin openstack compute service list
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
| ID | Binary         | Host                           | Zone     | Status  | State | Updated At                 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
|  2 | nova-scheduler | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:48.000000 |
|  5 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:48.000000 |
|  1 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:52.000000 |
|  3 | nova-compute   | stephenfin-devstack-controller | nova     | enabled | up    | 2021-11-30T17:25:48.000000 |
|  4 | nova-compute   | stephenfin-devstack-compute    | nova     | enabled | up    | 2021-11-30T17:25:50.000000 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+

# using explicit flag for admin cloud credentials
$ openstack --os-cloud=devstack-admin compute service list
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
| ID | Binary         | Host                           | Zone     | Status  | State | Updated At                 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
|  2 | nova-scheduler | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:48.000000 |
|  5 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:48.000000 |
|  1 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:25:52.000000 |
|  3 | nova-compute   | stephenfin-devstack-controller | nova     | enabled | up    | 2021-11-30T17:25:48.000000 |
|  4 | nova-compute   | stephenfin-devstack-compute    | nova     | enabled | up    | 2021-11-30T17:25:50.000000 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+

# using explicit flag for non-admin cloud credentials
$ openstack --os-cloud=devstack compute service list
Policy doesn't allow os_compute_api:os-services:list to be performed. (HTTP 403) (Request-ID: req-835a0142-e3d2-4024-abd7-012e1ed799b6)

# using explicit flag for non-admin cloud credentials and environment variable for admin cloud credentials
$ OS_CLOUD=devstack-admin openstack --os-cloud=devstack compute service list
Policy doesn't allow os_compute_api:os-services:list to be performed. (HTTP 403) (Request-ID: req-17bddec0-d078-4780-acd8-ca7ccca89db9)
```

However, in all cases, what's provided via environment variable or an explicit config option takes priority over whats in `cloud.yaml` itself. For example:

```
# using explicit flag for non-admin cloud credentials but with environment variable for other knobs
$ OS_USERNAME=admin OS_PROJECT_NAME=admin openstack --os-cloud=devstack compute service list
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
| ID | Binary         | Host                           | Zone     | Status  | State | Updated At                 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
|  2 | nova-scheduler | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:29:49.000000 |
|  5 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:29:48.000000 |
|  1 | nova-conductor | stephenfin-devstack-controller | internal | enabled | up    | 2021-11-30T17:29:44.000000 |
|  3 | nova-compute   | stephenfin-devstack-controller | nova     | enabled | up    | 2021-11-30T17:29:48.000000 |
|  4 | nova-compute   | stephenfin-devstack-compute    | nova     | enabled | up    | 2021-11-30T17:29:40.000000 |
+----+----------------+--------------------------------+----------+---------+-------+----------------------------+
```
