### ISSUE TITLE
Handle slightly more complex `clouds.yaml` formatting

### ISSUE THREAD

**Issue by sc68cal** [gophercloud/utils#68]
Each region of a cloud can have its own unique `auth_url` key, so that the schema appears like the following:

```yaml
---
clouds:
    mycloud:
        identity_api_version: 3
        endpoint_type: public
        image_format: raw
        auth:
            user_domain_name: 
            project_domain_name: 
            username: 
        regions:
            - name: Region 1
              values:
                auth:
                  auth_url: 
            - name: Region 2
              values:
                auth:
                  auth_url: 
            - name: Region 3
              values:
                auth:
                  auth_url: 
            - name: Region 4
              values:
                auth:
                  auth_url: 
            - name: Region 5
              values:
                auth:
                  auth_url: 
```

See the following issue for background

https://github.com/terraform-providers/terraform-provider-openstack/issues/405
